version: '3.5'

services:
  db_users:
    image: mysql:8
    container_name: db_users
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - "./docker/db_users:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: db_users
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
  db_files:
    image: mysql:8
    container_name: db_files
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - "./docker/db_files:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: db_files
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3307:3306"
  db_lists:
    image: mysql:8
    container_name: db_lists
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - "./docker/db_lists:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: db_lists
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3308:3306"
  rabbitmq:
    image: rabbitmq:3-management
    container_name: ${APP_NAME}_rabbitmq
    volumes:
      #- ./docker/rabbitmq/etc/:/etc/rabbitmq/
      - ./docker/rabbitmq/data/:/var/lib/rabbitmq/
      - ./docker/rabbitmq/logs/:/var/log/rabbitmq/
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    ports:
      - "5672:5672"
      - "15672:15672"
networks:
  default:
    name: microservices
